FROM ubuntu:20.04 AS base
ARG DEBIAN_FRONTEND="noninteractive"

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
RUN apt-get update && apt-get install -y \
    apt-transport-https software-properties-common 
RUN apt-get update && apt-get -y install --no-install-recommends  \

#FROM r-base AS r
#ARG DEBIAN_FRONTEND="noninteractive"

