FROM darachm/bioinf:bioinf-sam-bedtools-parallel AS htseq
ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y install --no-install-recommends  \
    python3 python3-pip
RUN python3 -m pip install --upgrade HTSeq numpy>=1.20.0

