FROM ubuntu:20.04 AS htseq
ARG DEBIAN_FRONTEND="noninteractive"

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
RUN apt-get update && apt-get -y install --no-install-recommends  \
    apt-transport-https software-properties-common 
RUN apt-get update && apt-get -y install --no-install-recommends  \
    python3 python3-pip
RUN python3 -m pip install HTSeq

