FROM darachm/bioinf:bioinf-sam-bedtools-parallel AS bioinf-kalign
ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y install --no-install-recommends \
    libtool 

WORKDIR /
RUN git clone https://github.com/TimoLassmann/kalign.git
WORKDIR /kalign
RUN ./autogen.sh && ./configure --disable-dependency-tracking && make && make check && make install
WORKDIR /

