FROM darachm/bioinf:bioinf-sam-bedtools-emboss-ncbi-ucsc-genometools-htslib AS latest
    #ARG DEBIAN_FRONTEND="noninteractive"
    RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        python3 python3-pip 
    RUN apt-get update && apt-get install -y --no-install-recommends \
        ripgrep 'ncbi-blast+' diamond-aligner infernal
    RUN git clone https://github.com/barricklab/pLannotate && \
        cd pLannotate && \
        sed -i 's/bokeh=2/bokeh==2/' requirements.txt && \
        sed -i 's/>=/==/' requirements.txt && \
        sed -i 's/pandas/pandas==1.3.5/' requirements.txt && \
        echo "altair==4.2.2" >> requirements.txt && \
        python3 setup.py install
    RUN plannotate setupdb

#https://github.com/barricklab/pLannotate/releases/download/v1.2.0/BLAST_dbs.tar.gz
#https://github.com/barricklab/pLannotate/archive/refs/tags/v1.2.0.tar.gz
