FROM ubuntu:20.04 AS bioinf-base

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ARG DEBIAN_FRONTEND="noninteractive"
RUN ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
RUN apt-get update 

RUN apt-get update && apt-get install -y --no-install-recommends \
    lsb-release apt-utils \
    gnupg2 software-properties-common git g++ gcc make gdb \
    wget curl gzip bzip2 lzma pigz xz-utils unzip \
    gawk mawk perl \
    zlib1g zlib1g-dev libbz2-dev liblz-dev liblzma-dev liblzma5 \
    libcurl4-openssl-dev \
    ncurses-base ncurses-bin libncurses5-dev autoconf \
    sqlite3 csvkit graphviz

FROM bioinf-base AS bioinf-python
    RUN apt-get update && apt-get install -y --no-install-recommends \
        python3-biopython python3-pip \
        pypy3
    RUN python3 -m pip install \
        PyYAML==6.0 \
        pandas==1.4.1 \
        scikit-learn==1.3.0 \
        jellyfish==0.9.0 \
        rapidfuzz==2.0.11 \
        pysam==0.19.0 \
        cycler==0.11.0 \
        fonttools==4.33.3 \
        jarowinkler==1.0.2 \
        kiwisolver==1.4.2 \
        matplotlib==3.5.2 \
        networkx==2.8 \
        scipy==1.10.1 \
        numpy==1.22.3 \
        packaging==21.3 \
        Pillow==9.1.0 \
        pyparsing==3.0.9 \
        python-dateutil==2.8.2 \
        seqfold==0.7.14 \
        rapidfuzz==2.0.11 \
        edlib==1.3.9 \
        tqdm \
        six==1.16.0

FROM bioinf-python AS bioinf-python-parallel
    WORKDIR /parallel
    RUN wget https://ftp.gnu.org/gnu/parallel/parallel-20201222.tar.bz2 \
        && \
        tar -xvjf parallel-20201222.tar.bz2
    WORKDIR /parallel/parallel-20201222 
    RUN mkdir /root/.parallel \
        && \
        ./configure && \
        make && \
        make install && \
        make clean && \
        touch /root/.parallel/will-cite
    WORKDIR /
    RUN rm -rf /parallel-20201222 /parallel-20201222.tar.bz2

FROM bioinf-python-parallel AS bioinf-sam
    WORKDIR /sam
    RUN wget https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2
    RUN tar -xvjf samtools-1.14.tar.bz2 && cd samtools-1.14 && ./configure --prefix=/usr && make && make install
    WORKDIR /

FROM bioinf-sam AS bioinf-sam-bedtools
    RUN apt-get update && apt-get install -y --no-install-recommends \
        bedtools

FROM bioinf-sam-bedtools AS bioinf-sam-bedtools-emboss
    RUN apt-get update && apt-get install -y --no-install-recommends \
        emboss

FROM bioinf-sam-bedtools-emboss AS bioinf-sam-bedtools-emboss-ncbi
RUN apt-get update && apt-get install -y --no-install-recommends \
    ncbi-blast+ ncbi-tools-bin

FROM bioinf-sam-bedtools-emboss-ncbi AS bioinf-sam-bedtools-emboss-ncbi-ucsc
RUN apt-get update && apt-get install -y --no-install-recommends \
    rsync
RUN rsync -aP hgdownload.soe.ucsc.edu::genome/admin/exe/linux.x86_64/ /usr/local/bin/

FROM bioinf-sam-bedtools-emboss-ncbi-ucsc AS bioinf-sam-bedtools-emboss-ncbi-ucsc-genometools
RUN apt-get update && apt-get install -y --no-install-recommends \
    genometools

FROM bioinf-sam-bedtools-emboss-ncbi-ucsc-genometools AS bioinf-sam-bedtools-emboss-ncbi-ucsc-genometools-htslib
    WORKDIR /htslib
    RUN wget https://github.com/samtools/htslib/releases/download/1.16/htslib-1.16.tar.bz2
    RUN tar -xvjf htslib-1.16.tar.bz2 && cd htslib-1.16 && ./configure --prefix=/usr && make && make install
    WORKDIR /


#FROM bioinf-sam-bedtools-emboss-ncbi-ucsc-genometools-htslib AS bioinf-sam-bedtools-emboss-ncbi-ucsc-genometools-htslib-seqkit
#    RUN apt-get update && apt-get install -y --no-install-recommends \
#        golang
#    RUN go get -v -u github.com/shenwei356/seqkit/v2/seqkit
#        go get -v -u github.com/shenwei356/seqkit/seqkit
#    WORKDIR /

     #graphviz default-jdk # for nextflow
# to install nextflow
#    apt-get update && apt-get -y install default-jdk graphviz curl 
#    cd / 
#    curl -s https://get.nextflow.io | bash
#    chmod a+rx /nextflow

