
##### GUPPY
FROM darachm/cuda-tensorflow:cuda-11-2 AS nanopore-repo
#-py-3-9-tf-2-6-2
    RUN apt-get update && apt-get -y install --no-install-recommends \
        wget gnupg2 lsb-release apt-utils curl \
        && \
        wget -O- https://cdn.oxfordnanoportal.com/apt/ont-repo.pub | apt-key add - \
        && \
        export PLATFORM=$(lsb_release -cs) \
        && \
        echo "deb http://cdn.oxfordnanoportal.com/apt ${PLATFORM}-stable non-free" | tee /etc/apt/sources.list.d/nanoporetech.sources.list \
        && \
        mkdir /opt/ont


# doesn't work
#FROM nanopore-repo AS guppy-gpu-5.0.15
##    RUN apt-get update && apt-get -y install --no-install-recommends \
##        ont-guppy=5.0.15-1~focal
#    RUN wget https://cdn.oxfordnanoportal.com/software/analysis/ont_guppy_5.0.15-1~focal_amd64.deb \
#        && \
#        dpkg -i ont_guppy_5.0.15-1~focal_amd64.deb 

FROM nanopore-repo AS guppy-gpu-6.3.8
    RUN apt-get update && apt-get -y install --no-install-recommends \
        ont-guppy=6.3.8-1~focal
    ENV PATH=$PATH:/opt/ont/ont-guppy/bin

#FROM nanopore-repo AS guppy-gpu-6.1.3
#    RUN apt-get update && apt-get -y install --no-install-recommends \
#        ont-guppy=6.1.3-1~focal
#
#FROM nanopore-repo AS guppy-gpu-6.0.1
#    RUN curl https://cdn.oxfordnanoportal.com/software/analysis/ont-guppy_6.0.1_linux64.tar.gz \
#        | tar -xzC /opt/ont 
#    ENV PATH=$PATH:/opt/ont/ont-guppy/bin
#
#FROM nanopore-repo AS guppy-gpu-6.1.1
#    RUN curl https://cdn.oxfordnanoportal.com/software/analysis/ont-guppy_6.1.1_linux64.tar.gz \
#        | tar -xzC /opt/ont 
#    ENV PATH=$PATH:/opt/ont/ont-guppy/bin
#
#FROM nanopore-repo AS guppy-cpu-6.1.1
#    RUN curl https://cdn.oxfordnanoportal.com/software/analysis/ont-guppy-cpu_6.1.1_linux64.tar.gz \
#        | tar -xzC /opt/ont 
#    ENV PATH=$PATH:/opt/ont/ont-guppy/bin

##### MEDAKA
FROM darachm/cuda-tensorflow:cuda-11-2-py-3-8-tf-2-5-2 AS medaka
    ARG DEBIAN_FRONTEND="noninteractive"
    
    #RUN apt-get update && apt-get -y install --no-install-recommends \
    #    wget gnupg2 lsb-release
    #    export PLATFORM=$(lsb_release -cs)
    #    wget -O- https://cdn.oxfordnanoportal.com/apt/ont-repo.pub | apt-key add -
    #    echo "deb http://cdn.oxfordnanoportal.com/apt ${PLATFORM}-stable non-free" | tee /etc/apt/sources.list.d/nanoporetech.sources.list
    #    apt-get update
    
    RUN apt-get update && apt-get -y install --no-install-recommends \
        make gcc zlib1g-dev libbz2-dev liblzma-dev \
        libcurl4 libcurl4-openssl-dev git git-lfs file autoconf libncurses5-dev
    RUN git lfs install
    
    WORKDIR /htslib
    RUN wget https://github.com/samtools/htslib/releases/download/1.13/htslib-1.13.tar.bz2
    RUN tar -vxjf htslib-1.13.tar.bz2
    WORKDIR /htslib/htslib-1.13
    RUN make 
    WORKDIR /
    
    WORKDIR /samtools
    RUN wget https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2
    RUN tar -xvjf samtools-1.14.tar.bz2 && cd samtools-1.14 && ./configure --prefix=/usr && make && make install
    WORKDIR /

    WORKDIR /parallel
    RUN wget https://ftp.gnu.org/gnu/parallel/parallel-20201222.tar.bz2
    RUN tar -xvjf parallel-20201222.tar.bz2
    WORKDIR /parallel/parallel-20201222 
    RUN ./configure && make && make install && make clean
    RUN mkdir /root/.parallel && touch /root/.parallel/will-cite
    WORKDIR /parallel
    #RUN rm -rf /parallel-20201222 && rm -rf /parallel-20201222.tar.bz2
    WORKDIR /

    WORKDIR /bcftools
    RUN wget https://github.com/samtools/bcftools/releases/download/1.13/bcftools-1.13.tar.bz2
    RUN tar -vxjf bcftools-1.13.tar.bz2
    WORKDIR /bcftools/bcftools-1.13
    RUN make
    WORKDIR /

    RUN update-alternatives --install /usr/bin/python python '/usr/bin/python3.8' 99
    RUN update-alternatives --install /usr/bin/python3 python3 '/usr/bin/python3.8' 99
    RUN apt-get update && apt-get -y install --no-install-recommends \
        bzip2 g++ zlib1g-dev libbz2-dev liblzma-dev libffi-dev \
        libncurses5-dev libcurl4-gnutls-dev libssl-dev curl \
        make cmake wget python3-all-dev python3-virtualenv python3.8-venv

    WORKDIR /minimap2
    RUN git clone https://github.com/lh3/minimap2 /minimap2 && cd /minimap2 && make 
    WORKDIR /
    
    RUN python3.8 -m pip install medaka==1.5.0
    #    cd /
    #    git clone https://github.com/nanoporetech/medaka.git
    #    cd medaka
    #    sed -i 's/tensorflow~=2.5.2/tensorflow~=2.5.1/' requirements.txt # already installed 
    #    sed -i 's/tensorflow/tensorflow-gpu/' requirements.txt
    #    make install
    ##    python3 -m easy_install /medaka/dist/medaka-1.4.4-py3.6-linux-x86_64.egg
    
    ENV PATH=$PATH:/htslib/htslib-1.13:/samtools/samtools-1.14:/bcftools/bcftools-1.13:/minimap2:/parallel-20201222/src 
    
    #    cd /medaka
    #    . ./venv/bin/activate


FROM medaka AS medaka-hack
    ARG DEBIAN_FRONTEND="noninteractive"
    RUN rm /usr/local/lib/python3.8/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so

FROM darachm/bioinf:bioinf-sam-bedtools AS racon
    ARG DEBIAN_FRONTEND="noninteractive"

    RUN apt-get update && apt-get -y install --no-install-recommends \
        build-essential cmake git zlib1g-dev libbz2-dev liblzma-dev 

    WORKDIR /minimap2
    RUN git clone https://github.com/lh3/minimap2 /minimap2 && cd /minimap2 && make 
    WORKDIR /

    WORKDIR /
    RUN git clone --recursive https://github.com/lbcb-sci/racon.git 
    WORKDIR /racon/build
    RUN cmake -DCMAKE_BUILD_TYPE=Release .. && make
    WORKDIR /

    ENV PATH=$PATH:/racon/build/bin:/minimap2

##### nanoplot
FROM darachm/bioinf:bioinf-base AS nanoplot
    RUN apt-get update && apt-get -y install --no-install-recommends \
        python3-pip python3-dev
    RUN python3 -m pip install NanoPlot

