FROM darachm/bioinf:bioinf-sam AS bioconda
ARG DEBIAN_FRONTEND="noninteractive"

# RUN apt-get update && apt-get -y install --no-install-recommends 

#    export PATH=${PATH}:/miniconda/miniconda/bin

WORKDIR /miniconda
RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh 
RUN sh -C Miniconda3-latest-Linux-x86_64.sh -b -p ./miniconda
#RUN PATH=${PATH}:/miniconda/miniconda/bin
ENV PATH=${PATH}:/miniconda/miniconda/bin
RUN conda init bash
RUN conda update --all
RUN conda config --add channels defaults
RUN conda config --add channels bioconda

FROM bioconda AS bioconda-pacbio
ARG DEBIAN_FRONTEND="noninteractive"

RUN conda install --channel bioconda bam2fastx bax2bam lima pbaa pbbam pbccs \
        pblaa pbmarkdup pbmm2 recalladapters minimap2

#    conda create --name pacbio bioconda python=2.7
#    make env for all?

