##### nanoplot
FROM darachm/bioinf:bioinf-base AS latest
    ARG DEBIAN_FRONTEND="noninteractive"
    RUN apt-get update && apt-get -y install --no-install-recommends \
        python3 make gcc g++ zlib1g-dev git 
#libbz2-dev liblzma-dev libcurl4 libcurl4-openssl-dev git #samtools 

    WORKDIR /
    RUN git clone https://github.com/fenderglass/Flye && cd Flye && make
    ENV PATH=$PATH:/Flye/bin


